# Generated by Django 5.2.6 on 2026-03-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carbonemission",
            name="sector",
            field=models.CharField(
                choices=[
                    ("Transport", "Transport"),
                    ("Industrial", "Industrial"),
                    ("Energy", "Energy"),
                    ("Agriculture", "Agriculture"),
                    ("Residential", "Residential"),
                    ("CO", "Carbon Monoxide"),
                ],
                max_length=50,
            ),
        ),
    ]
