# Generated by Django 5.2.6 on 2026-03-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_carbonemission_sector"),
    ]

    operations = [
        migrations.AddField(
            model_name="town",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="town",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
