# Generated by Django 5.2.6 on 2026-06-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_town_elevation_town_pop"),
    ]

    operations = [
        migrations.CreateModel(
            name="PollutionPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("pollutant_type", models.CharField(max_length=10)),
                ("predicted_value", models.FloatField()),
                ("prediction_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PollutionReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "pollutant_type",
                    models.CharField(
                        choices=[
                            ("CO", "Carbon Monoxide"),
                            ("NO2", "Nitrogen Dioxide"),
                            ("O3", "Ozone"),
                            ("SO2", "Sulfur Dioxide"),
                            ("PM25", "PM2.5"),
                            ("PM10", "PM10"),
                        ],
                        max_length=10,
                    ),
                ),
                ("value", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("source", models.CharField(default="sensor", max_length=50)),
                ("is_prediction", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="town",
            name="district",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="preferred_district",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="preferred_town",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="CarbonEmission",
        ),
        migrations.DeleteModel(
            name="District",
        ),
        migrations.DeleteModel(
            name="Town",
        ),
    ]
