# Generated by Django 5.2.6 on 2026-04-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0003_town_latitude_town_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="town",
            name="elevation",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="town",
            name="pop",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
